### PR TITLE
Fix #115: Partnerships page redesign

### LINKED ISSUE #115: Partnerships page redesign milestones
- [x] Obtain and minimize new photo.
- [x] Redesign hero card.
- [x] Implement instruction card for new partnership.
- [x] Remove old codes and unused CSS classes.

### PR DESCRIPTION
**Pull request by hoangviet1993**
- [x] Update hero card and put in new instructions for partnerships card.
- [x] Remove old codes and old assets.
- [x] Minimize new hero pictures.

Changes in this PR  are live at https://oppia-foundation-test-server.appspot.com/partnerships
Here are some screenshots:

Mobile (ip5/6):
partnerships_page_mobile

Tablet (iPad):
partnerships_page_tablet

Desktop:
partnerships_page_desktop

### CODE REVIEW

**Comment by hoangviet1993** [comment]
@rachelwchen Can you also help me review the new Partnerships page at https://oppia-foundation-test-server.appspot.com/partnerships ?

**Comment by rachelwchen** [comment]
Hi @hoangviet1993 -- thanks for implementing this!!

Three comments:
1 -- can we increase the left margin, so that the paragraph aligns with the rest of the page please? (See [1] with the dotted red lines)
2 -- let's decrease the spacing between the number and the text a little (see [2])
3 -- let's adjust the position a bit, so that each image and text align with each individual column (see [3]).

For reference:
Current --
Desktop-cur

Changes to be made --
Desktop-edit

**Comment by hoangviet1993** [comment]
Hi @rachelwchen 
I have made some changes according to your requests. Please let me know what you think!
> 2 -- let's decrease the spacing between the number and the text a little (see [2])

Done!
> 3 -- let's adjust the position a bit, so that each image and text align with each individual column (see [3]).

I have made the item text center aligned. I think it helps, what do you think?
> 1 -- can we increase the left margin, so that the paragraph aligns with the rest of the page please? (See [1] with the dotted red lines)
I made the hero textbox center aligned instead of left align like. I initially went with your suggestion (1) but I do not think it looks that much better in comparison to center aligning it(2).

(1)Left-align hero text box
screencapture-localhost-8080-partnerships-2019-07-15-18_23_24

(2)Center-align hero text box
Large view-width (>1700px)
screencapture-localhost-8080-partnerships-2019-07-15-19_18_03
Medium view-with (1355px)
screencapture-localhost-8080-partnerships-2019-07-15-19_15_19

Again, changes are live on: https://oppia-foundation-test-server.appspot.com/partnerships

**Comment by rachelwchen** [comment]
Thanks for getting this done so quickly! 

For the large-width view, is it possible to set the width for the text, so the text for (2) doesn't look too much "longer" than the other ones? Not sure if this will be a troublesome fix -- if so, feel free to disregard this :) otherwise I think it's good if other folks don't have further comments!

image

**Comment by dchen97** [comment]
Thanks for all the hard work on this! If all of the above comments from Rachel are resolved, then it LGTM as well!

**Comment by hoangviet1993** [comment]
>For the large-width view, is it possible to set the width for the text, so the text for (2) doesn't look too much "longer" than the other ones?
@rachelwchen Done! Thank you so much for the clear explanations.
@seanlip can you PTAL?

**Comment by seanlip** [comment]
Thanks a lot! Looks great IMO. Just one question, can you make the names of all the icon files lowercase? After that it's good to go.

**Comment by hoangviet1993** [comment]
@seanlip I have renamed the icon files and made the necessary adjustments. Can you PTAL?

**Comment by seanlip** [comment]
Hi @hoangviet1993, I'm having trouble reviewing the diff for the PR since my last review. Why did you need to force-push? That tends to overwrite history, we generally discourage it.

**Comment by hoangviet1993** [comment]
I was trying to squash the file-renaming together with another commit which changes a JS file. Do you want me to revert the force push?

**Comment by seanlip** [comment]
Let's leave it for now -- I'll take a full pass again. But next time, please prefer making multiple commits rather than doing any force-pushing -- that will make it easier for reviewers to review the diff since they last reviewed. Thanks!

**Comment by hoangviet1993** [comment]
Got it @seanlip. So sorry for the trouble since the forced push was over menial stuff. I will simply keep committing like usual.

**Comment by seanlip** [comment]
No problem! Thanks @hoangviet1993 :)

**Pull request merged**
