### PR TITLE
Dropdown navbar button and new sidenav links for new About pages

### PR DESCRIPTION
**Pull request by hoangviet1993**
This PR implements the dropdown button so as to provide the same hub for linking the two new "About" pages (Oppia and Foundation).
Changes in this PR are live at: https://oppia-foundation-test-server-1.appspot.com/

Desktop screenshot:

Screen Shot 2019-07-31 at 3 40 31 PM

Desktop gif:

Mobile sidenav screenshot:
Screen Shot 2019-07-31 at 4 03 05 PM

### CODE REVIEW

**Comment by hoangviet1993** [comment]
@rachelwchen and @dchen97  Can you PTAL?

**Comment by rachelwchen** [comment]
Looks good to me!

**Comment by dchen97** [comment]
Thanks Viet! The only note is that in the Mobile view, could you add "About" in front of "The Foundation" and "The Oppia Platform" to better clarify that these links are tied to an "About" page? So instead of saying "The Foundation" or "The Oppia Platform," it can say "About The Foundation" and "About The Oppia Platform."

Otherwise, everything else looks good!

**Comment by hoangviet1993** [comment]
> could you add "About" in front of "The Foundation" and "The Oppia Platform" to better clarify that these links are tied to an "About" page? So instead of saying "The Foundation" or "The Oppia Platform",

Done! Thanks for taking a look!.

> it can say "About The Foundation" and "About The Oppia Platform."

Screen Shot 2019-08-03 at 8 23 12 PM

**Comment by hoangviet1993** [comment]
@rachelwchen @dchen97 Anything else needs to be addressed here?

**Comment by rachelwchen** [comment]
Looks good to me!

**Pull request merged**
