### PR TITLE
Fix #64: Remove ng-view autoscroll config to preserve previous scroll location

### LINKED ISSUE #64: Clicking "Back" button should preserve relative position on page (as with other websites)
Go to any website (e.g. do a google search), scroll down to about the middle, and click a link. When you click the back button, you are taken back to the place on the previous page where you clicked the link.

However, when clicking the back button on the Foundation site, you are instead taken to the top of the page. It would be better to preserve the existing behaviour on the web instead (of taking the user back to the place in the previous page where the link was clicked).

### PR DESCRIPTION
**Pull request by hoangviet1993**
Fix #64  (I hope this is the fix, otherwise a prolonged PR is expected)
I think the test server should have the behavior that you are looking for @seanlip  

1. Go to home page. Scroll to a certain location.
2. Go to partnerships page.
3. Click back button. The browser view should remain at step 1 location.

Please lmk if there is something I am overlooking.

Changes are live at:
https://oppia-foundation-test-server.appspot.com/

### CODE REVIEW

**Comment by seanlip** [comment]
Ah, I don't think this is the fix I'm afraid. If you click the Partnerships page (step 2) then you start off in the middle of the page and not the top, as expected.

**Comment by hoangviet1993** [comment]
@seanlip Ah got it. So there is a catch after all!

How about now?
https://oppia-foundation-test-server.appspot.com/

**Comment by hoangviet1993** [comment]
@seanlip can you please be specific with your reproduction steps?

I am having difficulty to replicate it with the following behavior:

1. Navigate to home page using provided Url. Landed at hero section.
2. Navigate to partnerships page using navbar and scroll down to "evidence of our success".
3. Navigate to home page. Expect to be at hero section again.
4. Navigate to partnerships page using navbar. Landed at "evidence of our success" section.

(Can you clear browser temp files and stuff like that before hand)?

**Comment by seanlip** [comment]
Ah, sorry! Yes of course.

1. On large screen, navigate to home page and scroll down.
2. Click on Partnerships page in navbar and scroll down.
3. Click on top-left icon. Expect to be at top of home page but it seems to be in the middle.
4. Click on Partnerships page in navbar. Expect to be at top of partnerships page but it seems to land in the middle.

(Landing in the middle should only happen when Back button is clicked, but not on forward navigation. Also I confirm that I've cleared my cache.)

**Comment by seanlip** [comment]
In other words, navigating via navbar, or by typing in URL, should always land at top of page. It's only when clicking back that the scroll position should be remembered.

**Comment by hoangviet1993** [comment]
@seanlip 

Thank you so much for clarifying these details. I never really paid attention to these minute details and took them for granted as a user.

I have tested out these scenarios:
Scenario 1:
1. Navigate to home page and scroll down to "Partner with us".
2. Navigate to Partnerships page using navbar. Verify that page view is at top of page.
3. Click "Back" button. Page view is not back at home page's "Partner with us"

Scenario 2:
1. Navigate to home page and scroll down to "Partner with us".
2. Navigate to Partnerships page using using navbar. Verify that page view is at top of page.
3. Click Oppia foundation logo. Verify that page view is at top of page.

Scenario 3,4 (replicate the above scenarios using Url)

Can you PTAL again?

**Comment by hoangviet1993** [comment]
@seanlip I am not sure tbh. I think I can justify needing `$window.pageXOffset` when the page is scroll-able horizontally. And I think if I try (really hard), I can get the page to be scroll-able sideway. I don't really mind get of it tbh. What do you think should be the call here?

**Comment by seanlip** [comment]
Eh, either's fine I think :) Let's just merge it! Thanks!

**Pull request merged**
