### PR TITLE
Update some of the volunteer profiles.

### PR DESCRIPTION
**Pull request by seanlip**
Some notes:
- Reduced cache time because otherwise the new images and volunteer data don't load. I wonder if we should set cache time to 0 until we have some kind of release policy with build hash changes? Otherwise even if we update the page, it won't change in the browsers of people who have visited it before.
- I'm a bit concerned about the different image sizes. Do you think it's better if all the image sizes are the same and we fix a convention? If so, please let me know what you think would be best, and I can ask folks for updated photos.

Thanks!

### CODE REVIEW

**Comment by hoangviet1993** [comment]
I would also need to do something similar like in the hero image PR: making all images fixed in size and just have the div display a certain sized image statically.

Currently, images can just resize based on view-width/view-height freely.

**Comment by seanlip** [comment]
Hm, I could easily crop the images if we have a spec for what to crop them
to...

**Comment by hoangviet1993** [comment]
Jordan photo size is 3600x2400. When I was working on the initial setup, I get a sample photo of the same dimension and just plug it in. 

To clarify, here is my updated model for handling photos, which in hindsight should have been done in the first place:

1) get the highest res image possible
2) blow it up by 2x
3) display a fixed size (lets say width:250px for mobile and 500px for desktop).

Lmk if I have the wrong mindset/ incorrect assumptions here.
The final step would be integration testing with every other interaction/elements/user actions (flip the screen, run through the carousel to make sure images are not low-res/malformed, resize the browser, etc...)

This way, we would get away without having to retouch every single photo handed to us. We simply programmatically deal with it using a simple css rule.

**Comment by hoangviet1993** [comment]
With regards to this PR, I would say just get everything in. I will try to deal with it myself first, somehow.

By the next meeting, if I still am stuck at an unsatisfactory state, we could work it out from there.

**Comment by seanlip** [comment]
Thanks! Your approach seems reasonable to me, though I think we still might need some guidelines since otherwise we won't know whether to crop/scale/etc.

In any case, going ahead and merging now. Thanks!

**Pull request merged**
