### PR TITLE
Change h1 from 36px to 40px

### PR DESCRIPTION
**Pull request by dawsoneliasen**
As outlined in design feedback; main header size increase

### CODE REVIEW

**Comment by hoangviet1993** [comment]
Before and after screenshots? @dawsoneliasen

**Comment by dawsoneliasen** [comment]
@hoangviet1993 hmm how would a get a before version?

**Comment by hoangviet1993** [comment]
I mean you can always checkout master branch right?

**Comment by dawsoneliasen** [comment]
that didn't seem to do anything. could my browser be caching the other branch?

**Comment by seanlip** [comment]
Try opening the JS console in your browser (assuming it's Chrome), then click and hold on the refresh button next to the URL and select "Empty Cache and Hard Reload". Does that help?

**Comment by dawsoneliasen** [comment]
screencapture-localhost-8080-2018-09-14-07_59_29
screencapture-localhost-8080-2018-09-14-07_59_14
@seanlip yes! thank you

**Pull request merged**
