### PR TITLE
Initial config file for CircleCI

### PR DESCRIPTION
**Pull request by hoangviet1993**
Some preliminary testing have been done from my fork.
(it is from a different branch and I open a PR for that branch separately)

https://circleci.com/gh/hoangviet1993/foundation-website/tree/setupCircleCIConfig
https://github.com/hoangviet1993/foundation-website/pull/2

Can you authorize CircleCI from oppia/foundation-website end?

and enable the settings in the "Advanced settings" submenu called:
"Only build pull requests"
and
"Build forked pull requests"

screen shot 2018-09-09 at 10 55 52 am
 
screen shot 2018-09-09 at 10 56 20 am

screen shot 2018-09-09 at 10 56 16 am

P.S CircleCI sends email per commit build. I disable email notifications from them.

### CODE REVIEW

**Comment by seanlip** [comment]
Just to check -- why both CircleCI and TravisCI? Is the former a backup for the latter?

Also /cc @apb7 in case he is interested.

**Comment by hoangviet1993** [comment]
Yep, both are running the same bash commands. CIrcleCI doesn't run codecov though since I figured we only need one

**Comment by seanlip** [comment]
Ah OK. So the idea is to have both TravisCI and CircleCI run each time?

**Comment by hoangviet1993** [comment]
Yes! like this
screen shot 2018-09-09 at 1 57 46 pm

screen shot 2018-09-09 at 1 57 54 pm

**Comment by seanlip** [comment]
I'm trying to do this, but I don't seem to see a setting for Circle CI. The idea is to install it as a GitHub app, right?

If so, then I think you'll need to make a request to install Circle CI as a GitHub app and I can approve it. Could you do that please?

**Comment by seanlip** [comment]
Ah I think I need to merge this first. Let me try that.

**Pull request merged**
