### PR TITLE
Partnerships get involved redesign

### PR DESCRIPTION
**Pull request by hoangviet1993**
- [x] Use Capriola font only when needed(buttons, each body card header, ...)
- [x] Re-design "We are growing card" based on version A of mock ( and its mobile version)

Mock:
partnership_redesign_a
partnership_redesign_b_mobile

### CODE REVIEW

**Comment by hoangviet1993** [comment]
Some static photos:
Desktop (>1280px);
screencapture-localhost-8080-2018-09-12-20_17_15 1

Tablet (iPad, horizontal view)(600-1280px)
screencapture-localhost-8080-2018-09-12-20_16_41

Mobile (iPhone 5S)(<600px)
screencapture-localhost-8080-2018-09-12-20_15_29

**Comment by hoangviet1993** [comment]
Some GIF of resizing the re-designed portion:

**Comment by hoangviet1993** [comment]
@rachelwchen

Can you take a look please? :D

Changes are live on https://mail-app-214415.appspot.com/#!/

**Comment by kevinlee12** [comment]
Hi @hoangviet1993, I had one minor comment:
- Text is a bit too close to Matthew
image

Other than that, everything else looks good!

**Comment by hoangviet1993** [comment]
@kevinlee12 
I made the page's column smaller in width. Can you PTAL?
@rachelwchen 
1a) worlds -> world
1b) Character spacing: I did not alter any of the letter-spacing attributes. I have made all page's title description having the same spacing, font size and line height.
2) Done! PTAL.
3) I have made the image smaller. Does it look better now?
4) I agree, it should be "trials" and icon description text should now only have capitalization on the first letter oft the first word.
5) The email address will get updated once we do a final deployment. I used a global Javascript constant named ADMIN_EMAIL_ADDRESS to keep things in sync :)

**Comment by rachelwchen** [comment]
Thank you!! Amazing. My last comment would be that the picture of Matthew looks a little pixelated (even on a standard Macbook 13" screen) so maybe resizing that image smaller would help. Not sure if this is a priority though - I think we can always keep iterating on the artwork in the future.

**Comment by kevinlee12** [comment]
Hi @hoangviet1993, it looks the text for this panel got closer to the picture:
image

**Comment by hoangviet1993** [comment]
@kevinlee12 there are padding-left and padding-right attribute on the image.

1) If you are using the testing server, can you refresh your browser cache?

2) Are you checking out the branch and running localhost? If so, can you try pulling the latest changes, refresh browser cache? 

I am having difficulty replicating the issue of the text overlapping the image div.

**Comment by kevinlee12** [comment]
Yup, I'm using the test server on Firefox, it doesn't appear to be an issue on Chrome.

**Comment by hoangviet1993** [comment]
@kevinlee12 
can you refresh browser cache and take a look?
@rachelwchen 
I re-did the compression process, but this time with a PNG file and limit the image dimension to 250px(width). You should be seeing a smaller "Matthew" graphic now. Please refresh browser cache if you don't see anything changed.

**Comment by kevinlee12** [comment]
I’m away from my computer, but on mobile, the text on panel 1 can be slightly higher
Image

**Comment by hoangviet1993** [comment]
@kevinlee12 yep no rush, can you take a detailed look on mobile and provide a comprehensive list of feedbacks? I have paid a lot of attentions on mobile and think that I still can do better.

**Comment by kevinlee12** [comment]
Hi @hoangviet1993, I've also found a few more items:

**Desktop** (tested on Firefox)
- On half screen on desktop, the picture of the learner is stretched:
image
- On half screen, "Get in touch" panel text has a scrollbar (but does not exist on mobile nor Chrome):
image
- The hyperlink on "Email us" includes the space afterward
screenshot from 2018-09-14 19-02-30
- The spacing to the right of the text in "Get in touch" compared to "Empowering students in every community" is quite different. I'm not sure whether this was intentional, but wanted to point this out. 
image
image

**Mobile** (tested on iOS Safari)
- Image for "Empowering students in every community" is missing.
- Bar graph for "Evidence of our success" is also missing.
- The points for "We're ready to grow" can be emphasized more (ie. by bolding the text). (Don't let the screenshot size fool you, the phone is about 2-3x smaller than the screenshot :smile: )

**Comment by hoangviet1993** [comment]
@kevinlee12 For mobile,
1) The graphic asset for "Empowering..." section is not displayed on purpose.
2) I am unable to replicate this. Can you take a screenshot of it missing?

**Comment by kevinlee12** [comment]
My apologizes, I completely missed over the graph for 2, it is there!

**Comment by hoangviet1993** [comment]
For desktop,

The padding between the "Get in touch" text column and the form is intentional. 

This is because I want the "Get in touch" text column to be look smaller than the form. 

The "Contact us" card tlooks pretty unsightly when I get the text column to be 850px wide like the rest of the pages.

I think both section looks good to me though.

**Comment by hoangviet1993** [comment]
@kevinlee12 PTAL
Desktop
- [x] Fix overstretched student image.
- [x] 'Get in touch' text column has vertical scroll bar on FF.
- [ ] Spacing to the right of 'Get in touch' text column is intentional.
Mobile
- [ ] "Empowering" graphic is not displayed on purpose.
- [ ] Bar graph is not missing (non-issue)
- [x] Icon description text is now bolded. 
Changes are live at: https://oppia-foundation-test-server.appspot.com/

**Comment by kevinlee12** [comment]
Just a nit, the graph looks squashed in the horizontal direction on mobile. 


Everything else looks really nice!

**Pull request merged**
