### PR TITLE
Fix #65: Use proper Paypal form to redirect user to Paypal donate page.

### LINKED ISSUE #65: Donate buttons should point to correct places
This applies to both the Home page and the Donate page.

The buttons in this page should follow the same source code in the main Oppia website (on the /donate page). Otherwise, the buttons just end up redirecting directly to the paypal homepage, which is not the intended user experience.

### PR DESCRIPTION
**Pull request by hoangviet1993**
Fix #65 
Donate page:

Home page:

Changes are live at:
https://oppia-foundation-test-server.appspot.com/

### CODE REVIEW

**Comment by seanlip** [comment]
Also just a note, make sure the title / comment has something like "Fix #65" in it. That way GitHub will auto-close the issue once this gets merged.

Thakns!

**Comment by hoangviet1993** [comment]
I have resolved the merge conflict (that came in after the other PR got merged).
I did have the `Fix #65` in my PR description. Will include in the title next time. Thanks!

**Comment by hoangviet1993** [comment]
@kevinlee12
Can you check https://oppia-foundation-test-server.appspot.com/donate to see if the image is still too big on your phone(on landscape mode)?

**Comment by kevinlee12** [comment]
Hi @hoangviet1993, which image are you referring to? (if it's the "Your donation helps fund" image, then it still looks the same). Also, I noticed that both donation buttons go to PayPal and see no difference in the credit card page vs PayPal page (I should point out that I don't have an account with them).

**Comment by hoangviet1993** [comment]
@kevinlee12 
1) Woops, forgot to make commits. Mb there. Changes should be live now
2)Yea both of them leads to the same page.

**Comment by kevinlee12** [comment]
Ah, I did a re-check and it still looked like it was before, though it looks bit smaller on portrait mode, here's the screenshot:


When I scroll down, the url and navigation bar goes away, but I kept it here for context. By the way, I noticed that the Donate button is no longer darkened. 

As for the donation buttons, I would recommend removing one of them, but since the UX is being redesigned there, that comment doesn't really apply :smile:

**Comment by seanlip** [comment]
Ah yes, I dropped the highlighting on Donate at the top right, it was confusing because it suggested that the user was on the Donate page.

I think we'll keep both buttons for now, although we might change the link on one of them later.

**Comment by hoangviet1993** [comment]
Haha @kevinlee12 then I have no idea what to do here. I made the image's container has a 50% width (`min-width: 50%`).
Here is the screenshot from my ip6:
image-1
and from Chrome's Device ip5
screen shot 2018-09-18 at 7 26 20 am
screencapture-oppia-foundation-test-server-appspot-donate-2018-09-18-07_26_36

**Comment by kevinlee12** [comment]
Ah, thanks for the explanation @seanlip!

Hmm, I think this to do more with how Safari renders this, unfortunately I don't have a mac, so I can't help debug further. But from the behavior that I'm seeing, it looks like it's still using the width from portrait mode and zooming in, but I won't be able to say more since I don't have a mac.

**Comment by hoangviet1993** [comment]
Yea I think you are zooming in. Here is a recording of my phone.

ezgif com-video-to-gif

**Comment by hoangviet1993** [comment]
What is the problem that you need me to address?

**Comment by kevinlee12** [comment]
Trying to see if using CSS orientation keywords helps to fix the zoom issue. 

If it doesn't fix it, then we can leave it as-is.

**Comment by hoangviet1993** [comment]
Is iOS Safari auto-zooming when you navigate to the page? Can you at least post of a gif of you navigating to the page and this unwanted zooming behavior?

**Comment by kevinlee12** [comment]
Whoops, sorry, my last comment made no sense.

Let's leave it as-is. Unfortunately I can't shoot a gif over since I don't have a mac. It isn't auto-zooming, but rather not using the CSS rules as it did on your phone.

**Comment by kevinlee12** [comment]
In terms of behavior, I went to the the Donation Page, scrolled down to the funds panel, and then rotated my phone 90 degrees. As it rotated, I noticed the image getting larger. I'm running on iOS 12, so I'm not sure if that makes a difference.

**Comment by hoangviet1993** [comment]
I downloaded this app called [Record It](https://itunes.apple.com/us/app/record-it-screen-capture/id1245356545?mt=8), accessed the page and hit record.
I then emailed myself the .mov file, converted to .gif and put it up here.

I am sorry if this is too much to ask. I have tried replicating it in good faith butI was unable to.
Still I would love to see this bug in action though. Looks like iOS12 shipped with Safari 12. Can you check if the problem is replicable on iOS's Chrome?

**Comment by kevinlee12** [comment]
I've got the gif below, so it looks like Apple actually has a [built in recorder](https://support.apple.com/en-us/HT207935), so no app necessary:
ezgif-3-cba7cd35a3

**Comment by hoangviet1993** [comment]
Yea it is looking increasingly hard to replicate haha @kevinlee12 Can you still zoom out afterward? Can you try iOS Chrome and Firefox?

But yea, I don't think I can fix this without making super tiny image , like 100px width or something, since everything on your phone is zoomed in on portrait mode. Like everything look big when zoomed in. Can you scroll up to confirm that the hero section is also zoomed in?

If everything is zoomed in, I really think that the problem is stemming from my poor css usage here :(

The problem is sure, I can make 50px width image, but I would not want to go out of my way to detect browser version just to display a different version of an image tag.

I still haven't decided to jump aboard iOS 12 but once I felt it is stable. I will do so asap.

**Comment by kevinlee12** [comment]
I tried zooming out, but the gif that you saw was the most zoomed out. I don't have iOS Chrome, but tried it on Firefox. I don't think we'll get much luck since Apple requires all browser to use their rendering engine. As for the hero image, here's what I see:

Portrait


Landscape

**Comment by hoangviet1993** [comment]
@kevinlee12 I have reduced the max-width to 350px and deployed latest changes to https://oppia-foundation-test-server.appspot.com/donate. Can you check if it's not taking up the entire screen horizontally?

**Comment by kevinlee12** [comment]
it worked! :smile:

**Comment by hoangviet1993** [comment]
Yay... Looks like my initial read of the problem was totally off there 💯 . Thanks @kevinlee12 for being a patient saint all this time.

**Pull request merged**
