### PR TITLE
Update volunteer info.

### PR DESCRIPTION
**Pull request by seanlip**
Remove Apurv, Kevin Lee and Dawson; add Kevin Thomas and Anu.

(Further changes will come later.)

### CODE REVIEW

**Review by DubeySandeep — APPROVED** [review]
LGTM, Can we just use compressed images? I've tried compressing images to 100 kb (Currently its 500kb+)
Kevin: https://user-images.githubusercontent.com/16653571/112856302-45486580-90cd-11eb-8a25-b4bae8a6cc09.jpg
Anubhuti: https://user-images.githubusercontent.com/16653571/112856859-dcadb880-90cd-11eb-9358-25c5e7b85a5c.jpg

Should we use the above images^?

(Note: Earlier we had images on size 50 Kb and the container in which we show the images have 350px width.)

**Review by DubeySandeep — CHANGES_REQUESTED** [review]
I see `app/static/assets/images/volunteer/profile_images/yamama.jpeg` is deleted but it's still used in `app/static/pages/volunteer/VolunteerInfoDefinitions.js`, is that expected?

**Comment by seanlip** [comment]
Thanks @DubeySandeep!

- Ah, Yamama's file is not deleted, but its size has been reduced.
- The reduced-size images look great, thanks for the catch! I've updated the PR to use those instead.

Please take another look when you get a chance. Thanks!

**Review by DubeySandeep — APPROVED** [review]
LGTM!

(and sorry about the Yamama file deletion issue, GitHub just shows red color for deletion and green for insertion, I found that it also shows % which explains the reduction [and they have a great feature for comparing binary file changes])

**Comment by seanlip** [comment]
No worries! And oh yes, I just found that feature too. I thought the icon meant "copy" so I never clicked on it before :P

**Comment by DubeySandeep** [comment]
image
Looks like the test failed to download some depds. I've restarted the test!

**Comment by seanlip** [comment]
Thanks! I had restarted it too, actually, but it's stuck behind the concurrency limit.

**Pull request merged**
