### PR TITLE
Donate page milestone 3: Make hero image smaller

### PR DESCRIPTION
**Pull request by hoangviet1993**
This PR addresses Jordan's feedback(Aug 2018) on the donate page.
Since this PR addresses what I consider a pure visual problem. I expect this PR to be a conversation rather than the usual programming dissection.

I wonder if I have to call in Jordan or Rachel and ask them if this is what they are looking for.

The original design has the entire hero image visible, thus everything is in focus.

(Staging environment: https://mail-app-214415.appspot.com/#!/donate)
Now, the image is slightly cropped, since I limit div height to 600px.
Aesthetically, the image is slightly out of focus. (I think)We would need to do some photo editing to get the desired focus (adjust image length or something like that I am not exactly up to date with photography). I am open to other suggestions as well. 

Usually, a really long horizontal picture would work better for these type of image slide, like Rachel example (IBM Blockchain: https://www.ibm.com/blockchain)

I do not have access to photo-editing software nor the hardware to run them. I have been looking into some command line library that can do these photo adjustment and found some promising lead, like:
https://github.com/esimov/caire
or other library that can simply crop out photo using a specified dimensions.

However, I rather have someone who knows , at least more than I do, about image editing software to reconcile the designer feedback and produce a suitable cropped image for the Donate page

Should we be able to solve this hero image problem, we can apply the same solution on the main page too.

Please check out the deployed website for comparison
Some after pics:
screencapture-localhost-8080-2018-08-31-10_18_28

Non-opaque button close-up pic:
screen shot 2018-08-31 at 9 59 14 am

### CODE REVIEW

**Comment by hoangviet1993** [comment]
On different browser width, things do look better
screencapture-localhost-8080-2018-08-31-10_41_42
However, I want a complete solution to work across different viewport lengths and widths.

**Comment by rachelwchen** [comment]
1. I can help crop the photo so that the kid's face isn't cropped off! Feel free to send me the original file.

2. In terms of displaying the image in different viewports, if we're thinking about mobile, how does it look if we just remove that photo entirely on mobile? i.e. the photo only shows if the viewport width is greater than a certain value. OR, the photo gets moved down. Here's a photo of what I mean by that:
screen shot 2018-08-31 at 4 46 24 pm

**Comment by hoangviet1993** [comment]
@rachelwchen 
Here is the uncompressed version (Github link, click Download to get the image):
https://github.com/hoangviet1993/foundation-website/blob/2d9189d19796d8647cd633cad049f10259f0f295/static/images/donate_hero_card_image.png
Here is the compressed version
https://mail-app-214415.appspot.com/assets/images/donate/donate_hero_card_image.jpg

You can visit the site https://oppia-foundation-website.appspot.com/#!/donate on mobilescreencapture-oppia-foundation-website-appspot-2018-08-31-17_05_07

**Comment by rachelwchen** [comment]
image_resized

**Comment by hoangviet1993** [comment]
Desktop view-width (>1280xp):
screencapture-localhost-8080-2018-09-05-11_07_47
Tablet view-width (600-1280px) (iPad):
screencapture-localhost-8080-2018-09-05-11_07_29 1
Mobile view-width (<600px) (Pixel 2):
screencapture-localhost-8080-2018-09-05-11_06_32

**Comment by hoangviet1993** [comment]
Some GIF for resizing browser width on the hero image:

**Comment by hoangviet1993** [comment]
Changes in this PR are live at https://mail-app-214415.appspot.com/#!/donate

**Comment by hoangviet1993** [comment]
New button alignment!

**Pull request merged**
