### PR TITLE
Update text on home and some small design changes for the Home page.

### PR DESCRIPTION
**Pull request by seanlip**
Hi @hoangviet1993, starting to take a look at this in earnest and do a final pass.

Some notes:

- When clicking the back button, could we preserve the scroll location on the previous page somehow? I keep having the experience where I click a button in the middle of a page, then click Back and it takes me to the top of the page I was last on, which gets a bit annoying because I've lost the earlier context.
- For the donate buttons at the bottom of the home page, can we follow exactly the source code in the main Oppia website on the /donate page? I think paypal needs it done this way, otherwise it just redirects to the paypal homepage.

Thanks!

### CODE REVIEW

**Comment by seanlip** [comment]
Oh, one more thing: could we also have the cursor change to a pointer when hovering over the play button on the video? I think @unit-00 solved a similar issue when working on the Fractions landing page recently (see https://github.com/oppia/oppia/pull/5527).

**Comment by seanlip** [comment]
Update: I took a pass through the navbar, footer, Donate and About pages as well, and made small changes to these. Will save the volunteer/partnerships pages for a separate PR since those need more work.

I'll also file the three above-mentioned changes as issues.

Thanks!

**Comment by seanlip** [comment]
Filed #64, #65, #66.

**Comment by seanlip** [comment]
Thanks @hoangviet1993! Actually I like Roboto here, since the text is meant to be read. So I'm fine with how it looks, but do you have objections?

**Comment by hoangviet1993** [comment]
There is sort of a pattern for hero section in partnerships/donate/volunteer page.
i.e the hero header text is in Capriola and the hero description text is in Roboto.

Since the about page also has a header text and a description body text, I just want to bring it up to your attention. No strong feeling really.

**Comment by hoangviet1993** [comment]
How about the "As seen in"? Is there any reason it is Roboto and not Capriola?

It is short enough and would not make things hard to read.

**Comment by seanlip** [comment]
I wanted to distinguish that one from the other headers, because the stuff
below it is not text. I think that one should be treated more as regular
text than high-level header.

>

**Comment by hoangviet1993** [comment]
Got it! Thanks @seanlip

**Pull request merged**
