### PR TITLE
Adding invisible text to fix navigation bar's aria label error

### PR DESCRIPTION
**Pull request by hoangviet1993**
I have the fix for this warning shelved some time ago. Now that all the pages are in place. Let's get those warnings!

Before (onload):
screen shot 2018-08-04 at 10 49 01 am

After:
screen shot 2018-08-04 at 10 49 18 am

### CODE REVIEW

**Comment by hoangviet1993** [comment]
PTAL @seanlip One-liner fix for aria-label error.

**Comment by seanlip** [comment]
This is great, thanks for fixing the accessibility issues. But I'm confused about the fix. What button is the error actually referring to and how does your change address it? (I don't see an aria-label in the change you made.)

**Comment by hoangviet1993** [comment]
This came in after replacing the simple text " The Oppia Foundation" with the svg image.

ng-material 's navigation bar item always require a text element. Only then will the aria-label error goes away.

**Comment by seanlip** [comment]
OK, let's make sure we solve the problem properly for less-sighted users, and not just do something to fix the error message. Here's what you can do:

- Install the ChromeVox extension (or use VoiceOver on Mac, or something else)
- Turn it on 
- Dim your monitor (or just don't look at it)
- Go to the page and listen to it

Does it make sense? If you can't tell the structure of the page from listening to it then we need to add more ARIA tags in the right places, etc.

**Comment by hoangviet1993** [comment]
I did both setup : Mac's VoiceOver using Safari and ChromeVox on Chrome.

I would say I have much better time using ChromeVox, entire <p> or HTML element get read when I click on them, very straightforward out-of-the-box experience. I would highly recommend it for future usability testing. 

Safari's VoiceOver is quite confusing for me. I clicked on stuff and it only read parts of the word, unlike ChromeVox. I have to tinker around with the settings and then use tab in order to make VoiceOver read the entire <p> or element .

I did managed to get both to read the navbar's item label on click, that I just added in this PR.

However, I cannot use tab to make the voice-over software to read the "About", "Partnerships", "Donate" and "Volunteer" navigation bar item. Should I switch over to buttons instead of using md-navbar?

Overall, I felt this PR is in a good state with aria-labels added to all active elements.
PTAL @seanlip

**Comment by seanlip** [comment]
Oh, interesting. You can use left/right arrow keys on that demo but for some reason it doesn't work on the fourth one.

md-button sounds good. Do you want to do this in this PR, or merge it and do it in a separate one? Either is fine with me.

**Comment by hoangviet1993** [comment]
I added some color changes on hover/focus of the nav bar item to mirror that of Oppia.org. Some final pics:
Desktop:
screen shot 2018-08-05 at 8 09 12 pm

**Pull request merged**
